### ISSUE TITLE
Failed to lookup view

### ISSUE THREAD

**Issue by 420daunn** [zeusbyte/FiversCan#2]
Error: Failed to lookup view "auth/login.ejs" in views directory "/www/wwwroot/dom.top/views"
    at Function.render (/www/wwwroot/dom.top/node_modules/express/lib/application.js:597:17)
    at ServerResponse.render (/www/wwwroot/dom.top/node_modules/express/lib/response.js:1048:7)
    at exports.login (/www/wwwroot/dom.top/controllers/app/auth.js:5:20)
    at Layer.handle [as handle_request] (/www/wwwroot/dom.top/node_modules/express/lib/router/layer.js:95:5)
    at next (/www/wwwroot/dom.top/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/www/wwwroot/dom.top/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/www/wwwroot/dom.top/node_modules/express/lib/router/layer.js:95:5)
    at /www/wwwroot/dom.top/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:346:12)
    at next (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:175:3)
    at router (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/www/wwwroot/dom.top/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:328:13)
    at /www/wwwroot/dom.top/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:346:12)
    at next (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:280:10)
    at setLocale (/www/wwwroot/dom.top/middlewares/locale.js:25:9)
    at Layer.handle [as handle_request] (/www/wwwroot/dom.top/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:328:13)
    at /www/wwwroot/dom.top/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:346:12)

**Comment by tiger785aa** [comment]
> Error: Failed to lookup view "auth/login.ejs" in views directory "/www/wwwroot/dom.top/views" at Function.render (/www/wwwroot/dom.top/node_modules/express/lib/application.js:597:17) at ServerResponse.render (/www/wwwroot/dom.top/node_modules/express/lib/response.js:1048:7) at exports.login (/www/wwwroot/dom.top/controllers/app/auth.js:5:20) at Layer.handle [as handle_request] (/www/wwwroot/dom.top/node_modules/express/lib/router/layer.js:95:5) at next (/www/wwwroot/dom.top/node_modules/express/lib/router/route.js:149:13) at Route.dispatch (/www/wwwroot/dom.top/node_modules/express/lib/router/route.js:119:3) at Layer.handle [as handle_request] (/www/wwwroot/dom.top/node_modules/express/lib/router/layer.js:95:5) at /www/wwwroot/dom.top/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:346:12) at next (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:280:10) at Function.handle (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:175:3) at router (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/www/wwwroot/dom.top/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:328:13) at /www/wwwroot/dom.top/node_modules/express/lib/router/index.js:286:9 at Function.process_params (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:346:12) at next (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:280:10) at setLocale (/www/wwwroot/dom.top/middlewares/locale.js:25:9) at Layer.handle [as handle_request] (/www/wwwroot/dom.top/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:328:13) at /www/wwwroot/dom.top/node_modules/express/lib/router/index.js:286:9 at Function.process_params (/www/wwwroot/dom.top/node_modules/express/lib/router/index.js:346:12)

K
